### ISSUE TITLE
[Docs] - Add website showcase

### ISSUE THREAD

**Issue by matthew-carroll** [Flutter-Bounty-Hunters/static_shock#161]
Social proof helps convince developers to try packages. A great social proof for a static site generator is a showcase section in the docs website, which shows screenshots of a series of publicly visible websites that are generated with Static Shock.

Build a plugin for screenshotting websites and then use that to render a showcase in the Docs website.

**Comment by xdega** [comment]
Love this idea! 

If the projects have public code repos (as most Github Pages sites will), it would probably also be beneficial to add links to the code. That way it could also serve as a useful tool to help devs discover how to implement certain features, and serve as a learning tool.
