### ISSUE TITLE
Add the ability to set URL based on something besides directory structure and file name

### ISSUE THREAD

**Issue by csells** [Flutter-Bounty-Hunters/static_shock#32]
e.g. Permalink tag or policy

My blog content is arranged into folders by year (2500+ posts in a single folder isn't useful). I use a Permalink tag for HTML files. I use a policy of filename-based links for Markdown files. The folder the file is in is ignored.

**Comment by matthew-carroll** [comment]
#88 added a `basePath` property, which overrides the directory structure. This property can be applied en masse by adding it to a `_data.yaml` file within a directory, which then applies it to all sub-directory pages.

This ticket doesn't include sufficient info to know if #88 solves the problem, but I'm going to assume that it does. Feel free to re-open with more info if additional control is needed.
